services:
  redis:
    env_file:
      - .env
    image: redis:8-alpine
    restart: always
    volumes:
      - redis-data:/data
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  next-downloader-bot:
    image: vchikalkin/next-downloader-bot:latest
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
      - telegram-bot-api

  telegram-bot-api:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    env_file:
      - .env
    image: aiogram/telegram-bot-api:latest=
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api

volumes:
  telegram-bot-api-data:
  redis-data:
