services:
  redis:
    image: redis:8-alpine
    restart: always
    env_file:
      - .env
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  next-downloader-bot:
    image: '${DOCKERHUB_USERNAME}/next-downloader-bot:${BOT_IMAGE_TAG}'
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - telegram-bot-api
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    env_file:
      - .env
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

volumes:
  telegram-bot-api-data:
  redis-data:
