services:
  redis:
    image: redis:8-alpine
    restart: always
    env_file:
      - .env
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  next-downloader-bot:
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - telegram-bot-api

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    env_file:
      - .env
    # environment:
    #   TELEGRAM_API_ID: "<api-id>"
    #   TELEGRAM_API_HASH: "<api-hash>"
    ports:
      - '127.0.0.1:8081:8081'
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api

volumes:
  telegram-bot-api-data:
  redis-data:
