services:
  next-downloader-bot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
  telegram-bot-api:
    env_file:
      - .env
    image: aiogram/telegram-bot-api:latest
    # environment:
    #   TELEGRAM_API_ID: "<api-id>"
    #   TELEGRAM_API_HASH: "<api-hash>"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

volumes:
  telegram-bot-api-data:
