packages:
  - apps/*
  - packages/*
catalog:
  "@types/node": ^20
  "@vchikalkin/eslint-config-awesome": ^2.2.2
  dotenv-cli: ^7.4.4
  eslint: ^9.17.0
  husky: ^9.1.7
  lint-staged: ^15.2.10
  prettier: ^3.2.5
  rimraf: ^6.0.1
  typescript: ^5.7
  vite-tsconfig-paths: ^5.1.4
  vitest: ^2.1.8
  zod: ^3.24.1
